### ISSUE TITLE
OracleXAResource problem with proxies

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.jdbc#226]
There are issues describing a proxied Oracle XAResource usage:
* https://issues.redhat.com/browse/JWS-1943
* https://issues.apache.org/jira/browse/DBCP-570

We have to check how/if it affects Pax JDBC

**Comment by grgrzybek** [comment]
I reproduced it with podman-based Oracle DB and driver from https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/21.1.0.0/:
```
13:37:21 WARN [arjunacore.TransactionImple] (TransactionImple.java:766) : ARJUNA016138: Failed to enlist XA resource oracle.jdbc.driver.T4CXAResource@dbd8e44
oracle.jdbc.xa.OracleXAException: XAErr (-3): A resource manager error has occured in the transaction branch. ORA-24774 SQLErr (0)
	at oracle.jdbc.xa.OracleXAResource.convertError(OracleXAResource.java:1142) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.xa.client.OracleXAResource.start(OracleXAResource.java:253) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:740) [jta-5.10.6.Final.jar:5.10.6.Final]
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:422) [jta-5.10.6.Final.jar:5.10.6.Final]
	at org.ops4j.pax.jdbc.pool.dbcp2.impl.PooledDataSourceXATest.jtaTest(PooledDataSourceXATest.java:187) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.1.jar:4.13.1]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.1.jar:4.13.1]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.13.1.jar:4.13.1]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54) [junit-rt.jar:?]
Caused by: java.sql.SQLException: ORA-24774: cannot switch to specified transaction

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:628) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:557) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:552) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1312) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:726) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:291) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.driver.T4CTTIOtxse.doOTXSE(T4CTTIOtxse.java:175) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.driver.T4CXAResource.doStart(T4CXAResource.java:217) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.xa.client.OracleXAResource.start(OracleXAResource.java:248) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	... 30 more
```
