### ISSUE TITLE
MariaDB issue

### ISSUE THREAD

**Issue by Maurice-Betzel** [ops4j/org.ops4j.pax.jdbc#227]
###  java.lang.ClassNotFoundException: javax.sql.rowset.serial.SerialException not found by org.mariadb.jdbc

After downloading Karaf 4.2.11and installing pax-jdbc-mariadb, config, pool-aries and addind the following config:

_#Configuration for MariaDB persistence
dataSourceName=jpa/platform-repository-cf-xa
databaseName=platform_repository
osgi.jdbc.driver.class=org.mariadb.jdbc.Driver
osgi.jdbc.driver.name=mariadb
pool=aries
pool.poolMaxSize=4
pool.name=platformRepositoryXa
xa=true
user=
password=
url=jdbc:mariadb://127.0.0.1:3306/platform_repository_

 i get the following stackstrace, seems like the driver is missing imports?

_11:01:14.278 ERROR [CM Configuration Updater (Update: pid=org.ops4j.datasource.6e4229be-ca11-46fa-9419-12e5ff1be858)] [org.osgi.service.cm.ManagedServiceFactory, id=92, bundle=59/mvn:org.ops4j.pax.jdbc/pax-jdbc-config/1.5.0]: Unexpected problem updating configuration org.ops4j.datasource.6e4229be-ca11-46fa-9419-12e5ff1be858
java.lang.RuntimeException: javax/sql/rowset/serial/SerialException
        at org.ops4j.pax.jdbc.pool.aries.impl.AriesXaPooledDataSourceFactory.create(AriesXaPooledDataSourceFactory.java:71) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.PoolingWrapper.createDataSource(PoolingWrapper.java:41) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.DataSourceRegistration.createDs(DataSourceRegistration.java:138) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.DataSourceRegistration.<init>(DataSourceRegistration.java:82) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.DataSourceConfigManager.lambda$null$0(DataSourceConfigManager.java:85) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.ServiceTrackerHelper$1.addingService(ServiceTrackerHelper.java:132) ~[?:?]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) ~[osgi.core-6.0.0.jar:?]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) ~[osgi.core-6.0.0.jar:?]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[osgi.core-6.0.0.jar:?]
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) ~[osgi.core-6.0.0.jar:?]
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318) ~[osgi.core-6.0.0.jar:?]
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261) ~[osgi.core-6.0.0.jar:?]
        at org.ops4j.pax.jdbc.config.impl.ServiceTrackerHelper.track(ServiceTrackerHelper.java:141) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.DataSourceConfigManager.lambda$null$1(DataSourceConfigManager.java:81) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.ServiceTrackerHelper.track(ServiceTrackerHelper.java:147) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.ServiceTrackerHelper.track(ServiceTrackerHelper.java:86) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.DataSourceConfigManager.lambda$null$2(DataSourceConfigManager.java:80) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.ServiceTrackerHelper$1.addingService(ServiceTrackerHelper.java:132) ~[?:?]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) ~[osgi.core-6.0.0.jar:?]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) ~[osgi.core-6.0.0.jar:?]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[osgi.core-6.0.0.jar:?]
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) ~[osgi.core-6.0.0.jar:?]
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318) ~[osgi.core-6.0.0.jar:?]
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261) ~[osgi.core-6.0.0.jar:?]
        at org.ops4j.pax.jdbc.config.impl.ServiceTrackerHelper.track(ServiceTrackerHelper.java:141) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.ServiceTrackerHelper.track(ServiceTrackerHelper.java:86) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.DataSourceConfigManager.lambda$updated$3(DataSourceConfigManager.java:79) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.ServiceTrackerHelper.track(ServiceTrackerHelper.java:147) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.ServiceTrackerHelper.track(ServiceTrackerHelper.java:86) ~[?:?]
        at org.ops4j.pax.jdbc.config.impl.DataSourceConfigManager.updated(DataSourceConfigManager.java:78) ~[?:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceFactoryTracker.updated(ManagedServiceFactoryTracker.java:159) ~[!/:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceFactoryTracker.provideConfiguration(ManagedServiceFactoryTracker.java:93) [!/:?]
        at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1416) [!/:?]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:122) [!/:?]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:84) [!/:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NoClassDefFoundError: javax/sql/rowset/serial/SerialException
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:632) ~[?:?]
        at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150) ~[?:?]
        at org.mariadb.jdbc.MariaDbDataSource.getConnection(MariaDbDataSource.java:275) ~[?:?]
        at org.mariadb.jdbc.MariaDbDataSource.getXAConnection(MariaDbDataSource.java:453) ~[?:?]
        at org.apache.aries.transaction.jdbc.internal.Recovery$1.getNamedXAResource(Recovery.java:55) ~[?:?]
        at org.apache.geronimo.transaction.manager.RecoverTask.run(RecoverTask.java:49) ~[?:?]
        at org.apache.geronimo.transaction.manager.TransactionManagerImpl.registerNamedXAResourceFactory(TransactionManagerImpl.java:353) ~[?:?]
        at org.apache.aries.transaction.jdbc.internal.Recovery.recover(Recovery.java:47) ~[?:?]
        at org.apache.aries.transaction.jdbc.RecoverableDataSource.start(RecoverableDataSource.java:241) ~[?:?]
        at org.ops4j.pax.jdbc.pool.aries.impl.AriesXaPooledDataSourceFactory.create(AriesXaPooledDataSourceFactory.java:60) ~[?:?]
        ... 35 more
Caused by: java.lang.ClassNotFoundException: javax.sql.rowset.serial.SerialException not found by org.mariadb.jdbc [50]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639) ~[?:?]
        at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80) ~[?:?]
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:632) ~[?:?]
        at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150) ~[?:?]
        at org.mariadb.jdbc.MariaDbDataSource.getConnection(MariaDbDataSource.java:275) ~[?:?]
        at org.mariadb.jdbc.MariaDbDataSource.getXAConnection(MariaDbDataSource.java:453) ~[?:?]
        at org.apache.aries.transaction.jdbc.internal.Recovery$1.getNamedXAResource(Recovery.java:55) ~[?:?]
        at org.apache.geronimo.transaction.manager.RecoverTask.run(RecoverTask.java:49) ~[?:?]
        at org.apache.geronimo.transaction.manager.TransactionManagerImpl.registerNamedXAResourceFactory(TransactionManagerImpl.java:353) ~[?:?]
        at org.apache.aries.transaction.jdbc.internal.Recovery.recover(Recovery.java:47) ~[?:?]
        at org.apache.aries.transaction.jdbc.RecoverableDataSource.start(RecoverableDataSource.java:241) ~[?:?]
        at org.ops4j.pax.jdbc.pool.aries.impl.AriesXaPooledDataSourceFactory.create(AriesXaPooledDataSourceFactory.java:60) ~[?:?]
        ... 35 more_

**Comment by Maurice-Betzel** [comment]
The missing class is exported by the Felix framework:

javax.sql.rowset.serial                                    │ 0.0.0       │ 0  │ org.apache.felix.framework
javax.sql.rowset.spi                                        │ 0.0.0       │ 0  │ org.apache.felix.framework
javax.sql.rowset                                             │ 0.0.0       │ 0  │ org.apache.felix.framework
javax.sql                                                        │ 0.0.0       │ 0  │ org.apache.felix.framework

**Comment by grgrzybek** [comment]
Related to https://github.com/mariadb-corporation/mariadb-connector-j/pull/170

**Comment by grgrzybek** [comment]
For now, you simply can't install mariadb jdbc driver 2.7.2 and pax-jdbc-mariadb feature.
`pax-jdbc-mariadb` feature is:
```
    <feature name="pax-jdbc-mariadb" description="Provides JDBC Mariadb DataSourceFactory" version="1.5.0">
        <feature>pax-jdbc-spec</feature>

        <bundle dependency="true">mvn:org.mariadb.jdbc/mariadb-java-client/2.7.2</bundle>
        <bundle>mvn:org.ops4j.pax.jdbc/pax-jdbc-mariadb/1.5.0</bundle>
    </feature>
```

So instead of (in Karaf) doing `feature:install pax-jdbc-mariadb` you have to do:
```
feature:install pax-jdbc-spec
bundle:install mvn:org.ops4j.pax.jdbc/pax-jdbc-mariadb/1.5.0
bundle:install mvn:org.mariadb.jdbc/mariadb-java-client/2.4.4
```

Od because mariadb-java-client is specified with `dependency="true"`, you can install the driver first with version 2.4.4 and the the `pax-jdbc-spec` feature.

**Comment by Maurice-Betzel** [comment]
Indeed, reported to https://jira.mariadb.org/browse/CONJ-867 a few days ago, version 2.7.1 is functional under OSGi as well.

**Comment by grgrzybek** [comment]
I've created https://github.com/ops4j/org.ops4j.pax.jdbc/issues/230 to be fixed when new MariaDB driver is out
